### ISSUE TITLE
Docker Group is everywhere

### ISSUE THREAD

**Issue by alexb7217** [alexb7217/ubuntu-webdev-machine-setup#3]
roles/docker/tasks.main.yml

this code includes everything in the docker group

```
- name: add user to docker group
  user:
    name: "{{ local_username }}"
    append: yes
    groups:
      - docker
```

Find a way to be more discriminate
